-- tabelas
CREATE TABLE PESSOA(
ID_PESSOA INT IDENTITY(100,1) PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
SOBRENOME VARCHAR(50) NOT NULL,
RG VARCHAR(12) NOT NULL,
) 
GO
CREATE TABLE DETALHES_PESSOA(
ID_DETALHE_PESSOA INT IDENTITY (10,1) PRIMARY KEY,
ID_PESSOA INT FOREIGN KEY REFERENCES PESSOA(ID_PESSOA),
TELEFONE VARCHAR(15),
CONTATO VARCHAR(200),
PAIS VARCHAR(50),
ESTADO VARCHAR(25),
CIDADE VARCHAR(100),
ENDERECO VARCHAR(250),
NUMERO VARCHAR(20),
COMPLEMENTO VARCHAR(25)
)
GO
CREATE TABLE CARGO(
ID_CARGO INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (50)
)
GO
CREATE TABLE VENDEDOR(
ID_VENDEDOR INT IDENTITY(100,1) PRIMARY KEY,
ID_PESSOA INT FOREIGN KEY REFERENCES PESSOA(ID_PESSOA),
ID_CARGO INT FOREIGN KEY REFERENCES CARGO(ID_CARGO),
SALARIO MONEY,
DATA_EFETIVACAO DATE,
DATA_DESLIGAMENTO DATE
)
GO
CREATE TABLE CLIENTE(
ID_CLIENTE INT IDENTITY(10,1) PRIMARY KEY,
ID_PESSOA INT FOREIGN KEY REFERENCES PESSOA(ID_PESSOA)
)
GO
CREATE TABLE MARCA(
ID_MARCA TINYINT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(50)
)
GO
CREATE TABLE MODELO(
ID_MODELO INT IDENTITY(10,1) PRIMARY KEY,
ID_MARCA TINYINT FOREIGN KEY REFERENCES MARCA(ID_MARCA),
VALOR MONEY,
MODELO VARCHAR(50),
ANO_MODELO DATE,
PLACA VARCHAR(12),
ESTADO VARCHAR(10),
KM_RODADO FLOAT
)
GO
CREATE TABLE MEIO_PAGAMENTO(
ID_MEIO_PAGAMENTO INT IDENTITY(10,1) PRIMARY KEY,
TIPO VARCHAR(40)
)
GO
CREATE TABLE PEDIDO(
ID_PEDIDO INT IDENTITY(10,1) PRIMARY KEY,
ID_VENDEDOR INT FOREIGN KEY REFERENCES VENDEDOR(ID_VENDEDOR),
ID_MODELO INT FOREIGN KEY REFERENCES MODELO(ID_MODELO),
ID_MEIO_PAGAMENTO INT FOREIGN KEY REFERENCES MEIO_PAGAMENTO(ID_MEIO_PAGAMENTO)
)
GO
CREATE TABLE PAGAMENTO_PARCIAL(
ID_PAGAMENTO INT IDENTITY(10,1) PRIMARY KEY,
ID_PEDIDO INT FOREIGN KEY REFERENCES PEDIDO(ID_PEDIDO),
VALOR_ENTRADA MONEY,
VALOR_RESTANTE MONEY,
QUANTIDADE_PARCELAS TINYINT,
VALOR_PARCELAS MONEY,
DATA_COMPRA DATETIME DEFAULT GETDATE(),
DATA_FIM_GARANTIA DATETIME DEFAULT DATEADD(YEAR, +1, GETDATE()),
DATA_PREVISTA_TERMINO DATE,
)
GO 
CREATE TABLE PAGAMENTO_TOTAL(
ID_PAGAMENTO INT IDENTITY(10,1) PRIMARY KEY,
ID_PEDIDO INT FOREIGN KEY REFERENCES PEDIDO(ID_PEDIDO),
VALOR_PAGO MONEY,
DATA_COMPRA DATETIME DEFAULT GETDATE(),
DATA_FIM_GARANTIA DATETIME DEFAULT DATEADD(YEAR, +1, GETDATE())
)
GO
